In [1]:
import numpy as np

### python lists vs numpy arrays

In [7]:
#calculations are not possible on lists
python_list = [1, 2, 3, 4]
print((python_list) * 10)


[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]


In [8]:

numpy_array = np.array([1, 2, 3, 4])
print((numpy_array) * 10)

[10 20 30 40]


In [9]:
#adding things up
print(python_list + python_list)

print(numpy_array + numpy_array)


[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


### numpy operations

In [12]:
#finding size and shape
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(numpy_array.size)
print(numpy_array.shape)

10
(10,)


In [14]:
np_2d = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10)])
print(np_2d.size)
print(np_2d.shape)


10
(2, 5)


In [18]:
np_matrix = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13, 14, 15)])
print(np_matrix)

print(np_matrix.size)
print(np_matrix.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
15
(3, 5)


### reshaping an np array

In [19]:
#reshaping from (3,5) to (5,3)
numpy_matrix = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13, 14, 15)])
numpy_matrix = numpy_matrix.reshape(5, 3)
print(numpy_matrix)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


### retrieving specific value(s) form an np array

In [26]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(numpy_array[0:4]) 


[1 2 3 4]


In [30]:
np_matrix = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13, 14, 15)])
print(np_matrix[2,1:3])

[12 13]


### reversing the order

In [36]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np_array[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [40]:
np_matrix = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13, 14, 15)])
print(np_matrix[::-1])

[[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]


### min, max and sum

In [43]:
np_array = np.array([11, 12, 13, 14, 15])
print(np_array.min())
print(np_array.max())
print(np_array.sum())

11
15
65


In [50]:
### mean, median, variance, std

np_array = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(np_array.mean())
print(np.median(np_array)) ## np_array.median() does not work
print(np_array.var())
print(np_array.std())

15.5
15.5
8.25
2.8722813232690143


### rowwise / columnwise operations

In [53]:
np_matrix = np.array([(1, 2, 3, 4, 5), (6, 7, 8, 9, 10), (11, 12, 13, 14, 15)])

print(np_matrix,'\n')

print(np_matrix.sum(axis = 0),'\n')

print(np_matrix.sum(axis = 1),'\n')

print(np_matrix.sum(axis = None),'\n')


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

[18 21 24 27 30] 

[15 40 65] 

120 



In [55]:
### joining arrays

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
arr4 = np.array([10,11,12])
print(np.concatenate((arr1, arr2, arr3, arr4)))    
 


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [58]:

arr5 = np.array([[1,2,3],[0,0,0]])
arr6 = np.array([[0,0,0],[15,16,17]])
print(np.concatenate((arr5, arr6), axis = 1))  

[[ 1  2  3  0  0  0]
 [ 0  0  0 15 16 17]]


### getting an array stuffed with 0's

In [62]:
#these are all floats
all_zero = np.zeros((2,21))
print(all_zero)  
print(len(all_zero[0]))



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
21


In [63]:
#making them ints
print(np.zeros((2,21), dtype = np.int)) 



[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [64]:
#getting all ones
print(np.ones((1,21)))                   

print(np.ones((1,21), dtype = np.int)) 


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


### identity matrices

In [66]:
print(np.identity(6, dtype = np.int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [72]:
print(np.eye(6, 6, k = 0, dtype = np.int))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [74]:
#diagonal shift
print(np.eye(6, 6, k = 2, dtype = np.int))

[[0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [75]:
print(np.eye(6, 6, k = -2, dtype = np.int))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]]


### multipying matrices

In [80]:
#getting the dot product
arr_8 = np.array([ 1, 10 ])
arr_9 = np.array([ 4, 8 ])
print(np.dot(arr_8, arr_9))      

#getting the cross product (8-40)
print(np.cross(arr_8, arr_9))      


84
-32
